#!/usr/bin/env bash
# PreToolUse hook: blocks edits to styled-system/ (auto-generated by panda:codegen).

INPUT=$(cat)

FILE=$(echo "$INPUT" | python3 -c "
import sys, json
try:
    d = json.load(sys.stdin)
    print(d.get('tool_input', {}).get('file_path', ''))
except Exception:
    print('')
" 2>/dev/null || echo "")

if [[ "$FILE" == *"/styled-system/"* ]]; then
  echo ""
  echo "BLOCKED: styled-system/ is auto-generated by panda:codegen — do not edit manually."
  echo "  → To change tokens or conditions: edit panda.config.ts"
  echo "  → To add shared styles: edit src/styles/"
  echo "  → Regenerate: npm run panda:codegen"
  exit 2
fi

exit 0
